name: "snyk test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        run: snyk test --json-file-output=vuln.json --severity-threshold=critical

        continue-on-error: true
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Print json file
        run: cat vuln.json

        continue-on-error: true
      - name: Create Issues
        run: python3 create_issues.py -f vuln.json -t ${{ secrets.GH_TOKEN }} -r $GITHUB_REPOSITORY 
      
